// Self-hosts the three Google fonts the design uses (DM Sans, Instrument Serif, Inter Tight): downloads the same @font-face rules
// Google serves (same files, same unicode-range subsets, font-display: swap) and writes them to public/fonts + src/styles/fonts.css.
// File names carry a hash of the content, so they can be cached for a year (public/_headers).
// Run again only to update the fonts:  node scripts/perf/fetch-fonts.mjs
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const FAMILIES = "family=DM+Sans:wght@400;500;600&family=Instrument+Serif:ital@0;1&family=Inter+Tight:wght@400;500;600&display=swap";
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"; // a browser UA gets woff2 + unicode-range subsets
const ROOT = path.resolve(import.meta.dirname, "..", "..");
const FONTS = path.join(ROOT, "public", "fonts");
const css = await (await fetch(`https://fonts.googleapis.com/css2?${FAMILIES}`, { headers: { "user-agent": UA } })).text();
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

const rules = css.split("@font-face").slice(1).map((block) => ({
  family: /font-family:\s*'([^']+)'/.exec(block)[1],
  style: /font-style:\s*(\w+)/.exec(block)[1],
  weight: /font-weight:\s*(\d+)/.exec(block)[1],
  url: /url\((https:[^)]+)\)/.exec(block)[1],
  range: /unicode-range:\s*([^;]+);/.exec(block)?.[1] ?? "",
}));

fs.rmSync(FONTS, { recursive: true, force: true });
fs.mkdirSync(FONTS, { recursive: true });
const names = new Map(); // url -> file name
for (const r of rules) {
  if (names.has(r.url)) continue;
  const bytes = Buffer.from(await (await fetch(r.url)).arrayBuffer());
  const name = `${slug(r.family)}-${r.style}-${crypto.createHash("sha1").update(bytes).digest("hex").slice(0, 8)}.woff2`;
  fs.writeFileSync(path.join(FONTS, name), bytes);
  names.set(r.url, name);
}

let out = "/* Generated by scripts/perf/fetch-fonts.mjs from Google Fonts (SIL Open Font License). Do not edit. */\n";
for (const r of rules) out += `@font-face{font-family:'${r.family}';font-style:${r.style};font-weight:${r.weight};font-display:swap;src:url(/fonts/${names.get(r.url)}) format('woff2');${r.range ? `unicode-range:${r.range};` : ""}}\n`;
fs.writeFileSync(path.join(ROOT, "src", "styles", "fonts.css"), out);
// the body font and the headline italic are preloaded: both are on every first screen, and without the italic the headlines swap fonts late and shift the page (measured: CLS 0.18 on /blog on a slow phone, 0.00 with both preloaded; first paint is not slower)
const latin = (family, style) => names.get(rules.find((r) => r.family === family && r.style === style && r.range.startsWith("U+0000-00FF")).url);
fs.writeFileSync(path.join(ROOT, "src", "lib", "fonts.generated.ts"), `/* Generated by scripts/perf/fetch-fonts.mjs. Do not edit. */
export const FONT_PRELOAD: string[] = ${JSON.stringify([latin("DM Sans", "normal"), latin("Instrument Serif", "italic")])};
`);
console.log(`${names.size} font files, ${rules.length} @font-face rules`);
for (const [, n] of names) console.log("  ", n, fs.statSync(path.join(FONTS, n)).size);
