/* One file per section of the website (see docs/PAGE-CMS-ARCHITECTURE.md). Each exports its strict schema and the type inferred from it. */
export { homeHeroSchema } from "./home-hero.ts";
export type { HomeHeroSection } from "./home-hero.ts";
export { logoMarqueeSchema } from "./logo-marquee.ts";
export type { LogoMarqueeSection } from "./logo-marquee.ts";
export { showreelSchema } from "./showreel.ts";
export type { ShowreelSection } from "./showreel.ts";
export { whyStatsSchema } from "./why-stats.ts";
export type { WhyStatsSection } from "./why-stats.ts";
export { servicesColumnsSchema } from "./services-columns.ts";
export type { ServicesColumnsSection } from "./services-columns.ts";
export { caseShowcaseSchema } from "./case-showcase.ts";
export type { CaseShowcaseSection } from "./case-showcase.ts";
export { industriesGridSchema } from "./industries-grid.ts";
export type { IndustriesGridSection } from "./industries-grid.ts";
export { processStepsSchema } from "./process-steps.ts";
export type { ProcessStepsSection } from "./process-steps.ts";
export { reviewsCarouselSchema } from "./reviews-carousel.ts";
export type { ReviewsCarouselSection } from "./reviews-carousel.ts";
export { aboutHeroSchema } from "./about-hero.ts";
export type { AboutHeroSection } from "./about-hero.ts";
export { caseMosaicSchema } from "./case-mosaic.ts";
export type { CaseMosaicSection } from "./case-mosaic.ts";
export { principlesListSchema } from "./principles-list.ts";
export type { PrinciplesListSection } from "./principles-list.ts";
export { missionVisionSchema } from "./mission-vision.ts";
export type { MissionVisionSection } from "./mission-vision.ts";
export { timelineSchema } from "./timeline.ts";
export type { TimelineSection } from "./timeline.ts";
export { manifestoSchema } from "./manifesto.ts";
export type { ManifestoSection } from "./manifesto.ts";
export { officeClocksSchema, FLAGS } from "./office-clocks.ts";
export type { OfficeClocksSection } from "./office-clocks.ts";
export { faqAccordionSchema } from "./faq-accordion.ts";
export type { FaqAccordionSection } from "./faq-accordion.ts";
export { openRolesSchema } from "./open-roles.ts";
export type { OpenRolesSection } from "./open-roles.ts";
export { worksHeroSchema } from "./works-hero.ts";
export type { WorksHeroSection } from "./works-hero.ts";
export { worksGridSchema } from "./works-grid.ts";
export type { WorksGridSection } from "./works-grid.ts";
export { blogHeroSchema } from "./blog-hero.ts";
export type { BlogHeroSection } from "./blog-hero.ts";
export { blogFeaturedSchema } from "./blog-featured.ts";
export type { BlogFeaturedSection } from "./blog-featured.ts";
export { blogGridSchema } from "./blog-grid.ts";
export type { BlogGridSection } from "./blog-grid.ts";
export { contactIntroSchema } from "./contact-intro.ts";
export type { ContactIntroSection } from "./contact-intro.ts";
export { contactFormSchema } from "./contact-form.ts";
export type { ContactFormSection } from "./contact-form.ts";
export { ctaBandSchema } from "./cta-band.ts";
export type { CtaBandSection } from "./cta-band.ts";
export { reviewsCollectionSchema } from "./reviews-collection.ts";
export type { ReviewsCollectionSection } from "./reviews-collection.ts";
export { logosCollectionSchema, LOGO_STYLES } from "./logos-collection.ts";
export type { LogosCollectionSection } from "./logos-collection.ts";
export { siteRatingSchema } from "./site-rating.ts";
export type { SiteRatingSection } from "./site-rating.ts";
export { footerExtrasSchema } from "./footer-extras.ts";
export type { FooterExtrasSection } from "./footer-extras.ts";
export { caseStudyChromeSchema } from "./case-study-chrome.ts";
export type { CaseStudyChromeSection } from "./case-study-chrome.ts";
export { articleChromeSchema } from "./article-chrome.ts";
export type { ArticleChromeSection } from "./article-chrome.ts";
